version: '3.8'

services:
  postgres-stage0:
    image: postgres:15
    container_name: pg-stage0
    environment:
      POSTGRES_DB: ${POSTGRES_CHINOOK_DB}
      POSTGRES_USER: ${POSTGRES_CHINOOK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CHINOOK_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # монтирование Chinook_PostgreSql.sql для инициализации бд при первом запуске контейнера
      - ./Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/Chinook_PostgreSql.sql
    restart: unless-stopped
    networks:
      - airflow_network

networks:
  airflow_network:
    external: true
    name: stage0-source_airflow_network
