version: '3.8'

services:
  postgres_star_model:
    image: postgres:15
    container_name: postgres_star_model
    environment:
      # База для продуктовых данных (star-схема)
      POSTGRES_DB: star_model
      POSTGRES_USER: star
      POSTGRES_PASSWORD: star
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  # База для метаданных Airflow (внутри того же контейнера, но отдельная БД)
  postgres_airflow:
    image: postgres:15
    container_name: postgres_airflow
    environment:
      POSTGRES_DB: airflow_db
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data_airflow:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:2.10.0
    container_name: airflow_init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # Airflow использует свою БД airflow_db
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 2eCxJJrMGa9g5AKd0g7PTb4KGQ6FQJszTFKbqXX5u2M=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOGS_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres_airflow
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: 'no'
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.10.0
    container_name: airflow_webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 2eCxJJrMGa9g5AKd0g7PTb4KGQ6FQJszTFKbqXX5u2M=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOGS_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-init
    restart: unless-stopped
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.10.0
    container_name: airflow_scheduler
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: 2eCxJJrMGa9g5AKd0g7PTb4KGQ6FQJszTFKbqXX5u2M=
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOGS_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      - airflow-init
    restart: unless-stopped
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge
