version: '3.8'

services:
  postgres_star_model:
    image: postgres:15
    container_name: postgres_star_model
    environment:
      POSTGRES_DB: ${POSTGRES_STAR_DB}
      POSTGRES_USER: ${POSTGRES_STAR_USER}
      POSTGRES_PASSWORD: ${POSTGRES_STAR_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  postgres_airflow:
    image: postgres:15
    container_name: postgres_airflow
    environment:
      POSTGRES_DB: ${POSTGRES_AIRFLOW_DB}
      POSTGRES_USER: ${POSTGRES_AIRFLOW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AIRFLOW_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data_airflow:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:2.10.0
    container_name: airflow_init
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@postgres_airflow:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOGS_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./sql:/opt/airflow/sql
    depends_on:
      - postgres_airflow
    command: >-
      bash -c 'airflow db migrate && airflow users create --username "${AIRFLOW_USER}" --password "${AIRFLOW_PASS}" --firstname Admin --lastname User --role Admin --email "${AIRFLOW_EMAIL}" || true;
      airflow connections add postgres_star_model --conn-type postgres --conn-host postgres_star_model --conn-login "${POSTGRES_STAR_USER}" --conn-password "${POSTGRES_STAR_PASSWORD}" --conn-schema "${POSTGRES_STAR_DB}" --conn-port 5432 --overwrite;
      airflow connections add postgres_chinook --conn-type postgres --conn-host postgres-stage0 --conn-login "${POSTGRES_CHINOOK_USER}" --conn-password "${POSTGRES_CHINOOK_PASSWORD}" --conn-schema "${POSTGRES_CHINOOK_DB}" --conn-port 5432 --overwrite'
    restart: 'no'
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.10.0
    container_name: airflow_webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@postgres_airflow:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOGS_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__CORE__TEST_CONNECTION: "True"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-init
    restart: unless-stopped
    networks:
      - airflow_network
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./sql:/opt/airflow/sql

  airflow-scheduler:
    image: apache/airflow:2.10.0
    container_name: airflow_scheduler
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_AIRFLOW_USER}:${POSTGRES_AIRFLOW_PASSWORD}@postgres_airflow:5432/${POSTGRES_AIRFLOW_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOGS_FOLDER: /opt/airflow/logs
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    command: scheduler
    depends_on:
      - airflow-init
    restart: unless-stopped
    networks:
      - airflow_network
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./sql:/opt/airflow/sql

networks:
  airflow_network:
    driver: bridge
    external: true
    name: stage0-source_airflow_network
