version: '3.8'
services:
  postgres_olist:
    image: postgres:15
    container_name: postgres_olist_shared
    environment:
      POSTGRES_DB: olist_source
      POSTGRES_USER: olist
      POSTGRES_PASSWORD: olist
    ports:
      - "5433:5432"
    volumes:
      - olist_shared_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - olist_net

volumes:
  olist_shared_data:
networks:
  olist_net:
    name: olist_network
    external: true
